// Best-effort mapping of pre-1.13 numeric block IDs (+ data value) to modern block state names,
// for reading classic MCEdit-style .schematic files. Not exhaustive - obscure/modded legacy IDs
// fall back to a generic placeholder and are reported as a warning.

const WOOL_COLORS = [
  'white', 'orange', 'magenta', 'light_blue', 'yellow', 'lime', 'pink', 'gray',
  'light_gray', 'cyan', 'purple', 'blue', 'brown', 'green', 'red', 'black',
];

function byDataMod(names: string[], mod: number): Record<number, string> {
  const out: Record<number, string> = {};
  for (let d = 0; d < 16; d++) out[d] = names[d % mod] ?? names[0];
  return out;
}

export const LEGACY_BLOCKS: Record<number, string | Record<number, string>> = {
  0: 'minecraft:air',
  1: { 0: 'minecraft:stone', 1: 'minecraft:granite', 2: 'minecraft:polished_granite', 3: 'minecraft:diorite', 4: 'minecraft:polished_diorite', 5: 'minecraft:andesite', 6: 'minecraft:polished_andesite' },
  2: 'minecraft:grass_block',
  3: { 0: 'minecraft:dirt', 1: 'minecraft:coarse_dirt', 2: 'minecraft:podzol' },
  4: 'minecraft:cobblestone',
  5: byDataMod(['minecraft:oak_planks', 'minecraft:spruce_planks', 'minecraft:birch_planks', 'minecraft:jungle_planks', 'minecraft:acacia_planks', 'minecraft:dark_oak_planks'], 6),
  6: byDataMod(['minecraft:oak_sapling', 'minecraft:spruce_sapling', 'minecraft:birch_sapling', 'minecraft:jungle_sapling', 'minecraft:acacia_sapling', 'minecraft:dark_oak_sapling'], 6),
  7: 'minecraft:bedrock',
  8: 'minecraft:water',
  9: 'minecraft:water',
  10: 'minecraft:lava',
  11: 'minecraft:lava',
  12: { 0: 'minecraft:sand', 1: 'minecraft:red_sand' },
  13: 'minecraft:gravel',
  14: 'minecraft:gold_ore',
  15: 'minecraft:iron_ore',
  16: 'minecraft:coal_ore',
  17: byDataMod(['minecraft:oak_log', 'minecraft:spruce_log', 'minecraft:birch_log', 'minecraft:jungle_log'], 4),
  18: byDataMod(['minecraft:oak_leaves', 'minecraft:spruce_leaves', 'minecraft:birch_leaves', 'minecraft:jungle_leaves'], 4),
  19: { 0: 'minecraft:sponge', 1: 'minecraft:wet_sponge' },
  20: 'minecraft:glass',
  21: 'minecraft:lapis_ore',
  22: 'minecraft:lapis_block',
  23: 'minecraft:dispenser',
  24: { 0: 'minecraft:sandstone', 1: 'minecraft:chiseled_sandstone', 2: 'minecraft:cut_sandstone' },
  25: 'minecraft:note_block',
  26: 'minecraft:red_bed',
  27: 'minecraft:powered_rail',
  28: 'minecraft:detector_rail',
  29: 'minecraft:sticky_piston',
  30: 'minecraft:cobweb',
  31: { 0: 'minecraft:dead_bush', 1: 'minecraft:grass', 2: 'minecraft:fern' },
  32: 'minecraft:dead_bush',
  33: 'minecraft:piston',
  34: 'minecraft:piston_head',
  35: Object.fromEntries(WOOL_COLORS.map((c, i) => [i, `minecraft:${c}_wool`])),
  37: 'minecraft:dandelion',
  38: { 0: 'minecraft:poppy', 1: 'minecraft:blue_orchid', 2: 'minecraft:allium', 3: 'minecraft:azure_bluet', 4: 'minecraft:red_tulip', 5: 'minecraft:orange_tulip', 6: 'minecraft:white_tulip', 7: 'minecraft:pink_tulip', 8: 'minecraft:oxeye_daisy' },
  39: 'minecraft:brown_mushroom',
  40: 'minecraft:red_mushroom',
  41: 'minecraft:gold_block',
  42: 'minecraft:iron_block',
  43: { 0: 'minecraft:stone_slab', 1: 'minecraft:sandstone_slab', 2: 'minecraft:petrified_oak_slab', 3: 'minecraft:cobblestone_slab', 4: 'minecraft:brick_slab', 5: 'minecraft:stone_brick_slab', 6: 'minecraft:nether_brick_slab', 7: 'minecraft:quartz_slab' },
  44: { 0: 'minecraft:stone_slab', 1: 'minecraft:sandstone_slab', 2: 'minecraft:petrified_oak_slab', 3: 'minecraft:cobblestone_slab', 4: 'minecraft:brick_slab', 5: 'minecraft:stone_brick_slab', 6: 'minecraft:nether_brick_slab', 7: 'minecraft:quartz_slab' },
  45: 'minecraft:bricks',
  46: 'minecraft:tnt',
  47: 'minecraft:bookshelf',
  48: 'minecraft:mossy_cobblestone',
  49: 'minecraft:obsidian',
  50: 'minecraft:torch',
  51: 'minecraft:fire',
  52: 'minecraft:spawner',
  53: 'minecraft:oak_stairs',
  54: 'minecraft:chest',
  55: 'minecraft:redstone_wire',
  56: 'minecraft:diamond_ore',
  57: 'minecraft:diamond_block',
  58: 'minecraft:crafting_table',
  59: 'minecraft:wheat',
  60: 'minecraft:farmland',
  61: 'minecraft:furnace',
  62: 'minecraft:furnace',
  63: 'minecraft:oak_sign',
  64: 'minecraft:oak_door',
  65: 'minecraft:ladder',
  66: 'minecraft:rail',
  67: 'minecraft:cobblestone_stairs',
  68: 'minecraft:oak_wall_sign',
  69: 'minecraft:lever',
  70: 'minecraft:stone_pressure_plate',
  71: 'minecraft:iron_door',
  72: 'minecraft:oak_pressure_plate',
  73: 'minecraft:redstone_ore',
  74: 'minecraft:redstone_ore',
  75: 'minecraft:redstone_torch',
  76: 'minecraft:redstone_torch',
  77: 'minecraft:stone_button',
  78: 'minecraft:snow',
  79: 'minecraft:ice',
  80: 'minecraft:snow_block',
  81: 'minecraft:cactus',
  82: 'minecraft:clay',
  83: 'minecraft:sugar_cane',
  84: 'minecraft:jukebox',
  85: 'minecraft:oak_fence',
  86: 'minecraft:pumpkin',
  87: 'minecraft:netherrack',
  88: 'minecraft:soul_sand',
  89: 'minecraft:glowstone',
  90: 'minecraft:nether_portal',
  91: 'minecraft:jack_o_lantern',
  92: 'minecraft:cake',
  93: 'minecraft:repeater',
  94: 'minecraft:repeater',
  95: Object.fromEntries(WOOL_COLORS.map((c, i) => [i, `minecraft:${c}_stained_glass`])),
  96: 'minecraft:oak_trapdoor',
  97: { 0: 'minecraft:infested_stone', 1: 'minecraft:infested_cobblestone', 2: 'minecraft:infested_stone_bricks', 3: 'minecraft:infested_mossy_stone_bricks', 4: 'minecraft:infested_cracked_stone_bricks', 5: 'minecraft:infested_chiseled_stone_bricks' },
  98: { 0: 'minecraft:stone_bricks', 1: 'minecraft:mossy_stone_bricks', 2: 'minecraft:cracked_stone_bricks', 3: 'minecraft:chiseled_stone_bricks' },
  99: 'minecraft:brown_mushroom_block',
  100: 'minecraft:red_mushroom_block',
  101: 'minecraft:iron_bars',
  102: 'minecraft:glass_pane',
  103: 'minecraft:melon',
  104: 'minecraft:pumpkin_stem',
  105: 'minecraft:melon_stem',
  106: 'minecraft:vine',
  107: 'minecraft:oak_fence_gate',
  108: 'minecraft:brick_stairs',
  109: 'minecraft:stone_brick_stairs',
  110: 'minecraft:mycelium',
  111: 'minecraft:lily_pad',
  112: 'minecraft:nether_bricks',
  113: 'minecraft:nether_brick_fence',
  114: 'minecraft:nether_brick_stairs',
  115: 'minecraft:nether_wart',
  116: 'minecraft:enchanting_table',
  117: 'minecraft:brewing_stand',
  118: 'minecraft:cauldron',
  119: 'minecraft:end_portal',
  120: 'minecraft:end_portal_frame',
  121: 'minecraft:end_stone',
  122: 'minecraft:dragon_egg',
  123: 'minecraft:redstone_lamp',
  124: 'minecraft:redstone_lamp',
  125: byDataMod(['minecraft:oak_planks', 'minecraft:spruce_planks', 'minecraft:birch_planks', 'minecraft:jungle_planks', 'minecraft:acacia_planks', 'minecraft:dark_oak_planks'], 6),
  126: byDataMod(['minecraft:oak_slab', 'minecraft:spruce_slab', 'minecraft:birch_slab', 'minecraft:jungle_slab', 'minecraft:acacia_slab', 'minecraft:dark_oak_slab'], 6),
  127: 'minecraft:cocoa',
  128: 'minecraft:sandstone_stairs',
  129: 'minecraft:emerald_ore',
  130: 'minecraft:ender_chest',
  131: 'minecraft:tripwire_hook',
  132: 'minecraft:tripwire',
  133: 'minecraft:emerald_block',
  134: 'minecraft:spruce_stairs',
  135: 'minecraft:birch_stairs',
  136: 'minecraft:jungle_stairs',
  137: 'minecraft:command_block',
  138: 'minecraft:beacon',
  139: { 0: 'minecraft:cobblestone_wall', 1: 'minecraft:mossy_cobblestone_wall' },
  141: 'minecraft:carrots',
  142: 'minecraft:potatoes',
  143: 'minecraft:oak_button',
  144: 'minecraft:skeleton_skull',
  145: 'minecraft:anvil',
  146: 'minecraft:trapped_chest',
  147: 'minecraft:light_weighted_pressure_plate',
  148: 'minecraft:heavy_weighted_pressure_plate',
  149: 'minecraft:comparator',
  150: 'minecraft:comparator',
  151: 'minecraft:daylight_detector',
  152: 'minecraft:redstone_block',
  153: 'minecraft:nether_quartz_ore',
  154: 'minecraft:hopper',
  155: { 0: 'minecraft:quartz_block', 1: 'minecraft:chiseled_quartz_block', 2: 'minecraft:quartz_pillar' },
  156: 'minecraft:quartz_stairs',
  157: 'minecraft:activator_rail',
  158: 'minecraft:dropper',
  159: Object.fromEntries(WOOL_COLORS.map((c, i) => [i, `minecraft:${c}_terracotta`])),
  160: Object.fromEntries(WOOL_COLORS.map((c, i) => [i, `minecraft:${c}_stained_glass_pane`])),
  161: byDataMod(['minecraft:acacia_leaves', 'minecraft:dark_oak_leaves'], 2),
  162: byDataMod(['minecraft:acacia_log', 'minecraft:dark_oak_log'], 2),
  163: 'minecraft:acacia_stairs',
  164: 'minecraft:dark_oak_stairs',
  165: 'minecraft:slime_block',
  166: 'minecraft:barrier',
  167: 'minecraft:iron_trapdoor',
  168: { 0: 'minecraft:prismarine', 1: 'minecraft:prismarine_bricks', 2: 'minecraft:dark_prismarine' },
  169: 'minecraft:sea_lantern',
  170: 'minecraft:hay_block',
  171: Object.fromEntries(WOOL_COLORS.map((c, i) => [i, `minecraft:${c}_carpet`])),
  172: 'minecraft:terracotta',
  173: 'minecraft:coal_block',
  174: 'minecraft:packed_ice',
  175: { 0: 'minecraft:sunflower', 1: 'minecraft:lilac', 2: 'minecraft:tall_grass', 3: 'minecraft:large_fern', 4: 'minecraft:rose_bush', 5: 'minecraft:peony' },
  176: 'minecraft:white_banner',
  177: 'minecraft:white_wall_banner',
  178: 'minecraft:daylight_detector',
  179: { 0: 'minecraft:red_sandstone', 1: 'minecraft:chiseled_red_sandstone', 2: 'minecraft:cut_red_sandstone' },
  180: 'minecraft:red_sandstone_stairs',
  181: 'minecraft:red_sandstone_slab',
  182: 'minecraft:red_sandstone_slab',
  183: 'minecraft:spruce_fence_gate',
  184: 'minecraft:birch_fence_gate',
  185: 'minecraft:jungle_fence_gate',
  186: 'minecraft:dark_oak_fence_gate',
  187: 'minecraft:acacia_fence_gate',
  188: 'minecraft:spruce_fence',
  189: 'minecraft:birch_fence',
  190: 'minecraft:jungle_fence',
  191: 'minecraft:dark_oak_fence',
  192: 'minecraft:acacia_fence',
  193: 'minecraft:spruce_door',
  194: 'minecraft:birch_door',
  195: 'minecraft:jungle_door',
  196: 'minecraft:acacia_door',
  197: 'minecraft:dark_oak_door',
  198: 'minecraft:end_rod',
  199: 'minecraft:chorus_plant',
  200: 'minecraft:chorus_flower',
  201: 'minecraft:purpur_block',
  202: 'minecraft:purpur_pillar',
  203: 'minecraft:purpur_stairs',
  204: 'minecraft:purpur_slab',
  205: 'minecraft:purpur_slab',
  206: 'minecraft:end_stone_bricks',
  207: 'minecraft:beetroots',
  208: 'minecraft:grass_path',
  209: 'minecraft:end_gateway',
  210: 'minecraft:repeating_command_block',
  211: 'minecraft:chain_command_block',
  212: 'minecraft:frosted_ice',
  213: 'minecraft:magma_block',
  214: 'minecraft:nether_wart_block',
  215: 'minecraft:red_nether_bricks',
  216: 'minecraft:bone_block',
  217: 'minecraft:structure_void',
  218: 'minecraft:observer',
  219: 'minecraft:white_shulker_box',
  251: Object.fromEntries(WOOL_COLORS.map((c, i) => [i, `minecraft:${c}_concrete`])),
  252: Object.fromEntries(WOOL_COLORS.map((c, i) => [i, `minecraft:${c}_concrete_powder`])),
};

export function legacyIdToName(id: number, data: number): { name: string; known: boolean } {
  const entry = LEGACY_BLOCKS[id];
  if (entry === undefined) return { name: `minecraft:unknown_legacy_${id}`, known: false };
  if (typeof entry === 'string') return { name: entry, known: true };
  const name = entry[data] ?? entry[0];
  if (name === undefined) return { name: `minecraft:unknown_legacy_${id}_${data}`, known: false };
  return { name, known: true };
}
